### ISSUE TITLE
Name suggestions needed. 

### ISSUE THREAD

**Issue by Githubyte** [CaddyDz/EnglishWorlds#2]
This is an area where we suggest some cool catchy names for this social network.

**Comment by CaddyDz** [comment]
I could think of a shortened abbreviation of "I am Dz And I Speak English"  
It could work 👊

**Comment by xXMrObviousXx** [comment]
Shouldn't this be asked in a group?

**Comment by CaddyDz** [comment]
I don't think they would be interested before 0.1

**Comment by Githubyte** [comment]
First of all , what's your idea about this? ..who is your audience ? , are you willing to make it as national or global or just for the I'm dz community ?

**Comment by CaddyDz** [comment]
Okay ! so as a start I'm going to import the group members through the Facebook API.  
so for sure it's national but there will be no IP restrictions
Our audience is any Algerian who wants to learn English with friends and have fun while doing so

**Comment by 13makk37** [comment]
DzEnglishOnline
D.E.O ? .-.

**Comment by CaddyDz** [comment]
lol ! the O is an obvious word and should be omitted @13makk37 but thanks for your suggestions

**Comment by Githubyte** [comment]
DzAnglophones

**Comment by Githubyte** [comment]
AngloAlgerians

**Comment by Githubyte** [comment]
ESA : English Speaking Algerians

**Comment by Githubyte** [comment]
Algeria English Network AEN

**Comment by Githubyte** [comment]
The name isn't that important , you have a website like VK has millions of users and no one would argue about the name...

**Comment by Githubyte** [comment]
It may matter a little bit when users start using it as a verb ..(like: "hey, facebook me later")

**Comment by Githubyte** [comment]
Cafe Caddy

**Comment by Githubyte** [comment]
Caddy hub

**Comment by Githubyte** [comment]
Caddy English

**Comment by Githubyte** [comment]
Nerds cemetery

**Comment by Githubyte** [comment]
Speaky_English  
lol

**Comment by Githubyte** [comment]
Espeaky_l'anglais_ya_kho_wachbik

**Comment by CaddyDz** [comment]
hhhhhhhh you killed me

**Comment by DevBadi** [comment]
Whyy broo !

**Comment by DevBadi** [comment]
I didnt find u on fb

**Comment by CaddyDz** [comment]
I explicitly said that I'm leaving in a post and populated it with links to contact me somewhere else as alternative solution @DevBadi

**Comment by Githubyte** [comment]
Seen nothing , how stupid is that, you should sent me a dedicated msg..

**Comment by CaddyDz** [comment]
I'm pretty sure you knew I was leaving, add to that... Am not that hard to find

**Comment by Githubyte** [comment]
Do you receive a notification when I leave a msg in Gitter?

**Comment by CaddyDz** [comment]
I didn't because you didn't @Githubyte

**Comment by DevBadi** [comment]
Salim where are you

i need to talk to you thanks

2017-02-08 8:48 GMT+01:00 Salim Djerbouh <notifications@github.com>:

**Comment by CaddyDz** [comment]
I'm always here @DevBadi   
as well as chatting live on [Gitter](https://gitter.im/EnglishDz/Lobby)  
I also have a Twitter account [here](https://twitter.com/Saly3301)

**Comment by DevBadi** [comment]
Text me on private

**Comment by CaddyDz** [comment]
GitHub doesn't support private messaging and I don't have your Twitter account @DevBadi

**Comment by DevBadi** [comment]
My email broo use email
Merci

On 24 Feb 2017 14:25, "Salim Djerbouh" <notifications@github.com> wrote:

GitHub doesn't support private messaging and I don't have your Twitter
account @DevBadi <https://github.com/DevBadi>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CaddyDz/English/issues/2#issuecomment-282290326>, or mute
the thread

**Comment by CaddyDz** [comment]
I don't have your email either ! It's hidden from your GitHub profile

**Comment by DevBadi** [comment]
ayoubbouchedoub@gmail.com

**Comment by Githubyte** [comment]
Notification *** : Someone left a message for you @CaddyDz

**Comment by Githubyte** [comment]
Here, now I'm working as a bot .

**Comment by CaddyDz** [comment]
I got him! He's my friend on Discord now.
Thanks anyway @Githubyte

**Comment by xpack94** [comment]
i suck with names

**Comment by CaddyDz** [comment]
@xpack94 we all are xD

**Comment by MohamedAmine-C** [comment]
i would suggest Espeaky :p

**Comment by CaddyDz** [comment]
xD xD xD kichghol wach kho tspeaky Anglais 😛

**Comment by CaddyDz** [comment]
I totally agree with @Illusion3301   
The purpose of the website is to improve one's English by practice & fun, that's what the group was for and we should pass that task here with drastic forward improvements.  
It's not just for Algerians so we're certainly omitting `DZ`
The word `English` should stick tho
What do you suggest?

**Comment by abdoumjr** [comment]
I agree

**Comment by Illusion3301** [comment]
you can show the variety of the English language since it's spoken as 1st, 2nd and FL/SL by just name it WORLD OF ENGLISHES since we have so many accents /englishes, there's spanglish as an example
there're scholars who support this btw 
Chew (1991) argues for an IAL, namely, an international auxiliary language. She believes that ''We need a worldview of English, which recognizes that it no longer belongs exclusively to its native speakers. We must realise that when any language becomes international in character, it cannot be bound to any culture. It cannot be owned by its native speakers'' (p 43). She states further that ''the English language has to be denationalized "(p 44). 
part of my research tho :3

**Comment by CaddyDz** [comment]
Ooh WOW!! intensely impressive
For SEO purposes, the words has to be dictionary scoped so I think we'll go with `World Of English` and https://worldofenglish.com/  or https://englishworld.com as a domain name

**Comment by abdoumjr** [comment]
WOE.com

**Comment by abdoumjr** [comment]
They key is  having active admins,
And posts must be aproved

**Comment by Illusion3301** [comment]
active yes, useless yes ofc :3

**Comment by CaddyDz** [comment]
Taken

**Comment by CaddyDz** [comment]
woe.com and all top level domain extensions are taken @abdoumjr   
@Illusion3301 We are going to implement algorithms to ensure high quality posts and members only

**Comment by CaddyDz** [comment]
# Chosen Name "English Worlds"
Thanks @Githubyte @Illusion3301 @xXMrObviousXx @13makk37 @DevBadi @xpack94 @MohamedAmine-C @5nai3r @13makk37 @Yasmine-mnsr 
Congratulations 🎉 the name is chosen to be `English Worlds` 🎊 
I have purchased and parked the domain name https://englishworlds.com 
You can preview the v0.1.2 following that link

**Comment by bsoumeya** [comment]
illusion3301 but what's this?

**Comment by abdoumjr** [comment]
Congratulations

**Comment by CaddyDz** [comment]
@bsoumeya it's a project I've been working on for some time now
