### ISSUE TITLE
Install PHP zip extension on Scrutinizer CI

### ISSUE THREAD

**Issue by CaddyDz** [CaddyDz/EnglishWorlds#241]
Scrutinizer CI fails when installing composer dependencies, specifically `laravel/dusk` which requires ext-zip

**Comment by dyaskur** [comment]
did you solved this problem?

**Comment by CaddyDz** [comment]
@dyaskur no I decided I don't care

**Comment by dyaskur** [comment]
below is how I solved
https://stackoverflow.com/a/65379409/2671470

**Comment by CaddyDz** [comment]
Well that doesn't work, see [this](https://scrutinizer-ci.com/g/CaddyDz/EnglishWorlds/inspections/9e46fd6d-823c-458e-a892-39a8ccb632e7/log)

![image](https://user-images.githubusercontent.com/13698160/102806966-19c32a00-43be-11eb-9eb1-e72651789d02.png)

**Comment by dyaskur** [comment]
it's worked, maybe it's mean already installed so just need to load the extension.
check my finished test:
https://scrutinizer-ci.com/g/dyaskur/interview-case-study/inspections/7c96b218-a991-4e26-a256-dfbe1d99bd7a/log
before I changed it error:
https://scrutinizer-ci.com/g/dyaskur/interview-case-study/inspections/a43a7a20-4d8a-46e4-b9be-40f6badd9bf4/log
